-- CONSULTAS
-- 1. Top 10 de los vendedores que han concretado más ventas.
EXPLAIN PLAN FOR SELECT CONCAT(NOMBRE_VENDEDOR,CONCAT( ' ',APELLIDO_VENDEDOR)) as VENDEDOR FROM(
    SELECT NOMBRE_VENDEDOR, APELLIDO_VENDEDOR, COUNT(v.ID_VENDEDOR) AS VENTAS
    FROM ZAPATERIA.VENDEDOR v
    INNER JOIN ZAPATERIA.Factura f ON f.ID_VENDEDOR = v.ID_VENDEDOR
    GROUP BY v.ID_VENDEDOR, NOMBRE_VENDEDOR, APELLIDO_VENDEDOR
    ORDER BY VENTAS DESC
    )WHERE rownum<=10;
    
    SELECT * FROM TABLE (dbms_xplan.display);

-- 2. Top 3 de productos más vendidos en el año 2020.
EXPLAIN PLAN FOR SELECT PRODUCTO FROM (
    SELECT p.ID_PRODUCTO, p.NOMBRE_PRODUCTO AS PRODUCTO, SUM(d.CANTIDAD) AS CANTIDAD --TO_CHAR(f.FECHA_FACTURA,'yyyy') AS ANIO,CONCAT(TO_CHAR(f.FECHA_FACTURA,'MM'),CONCAT('-',TO_CHAR(f.FECHA_FACTURA,'MONTH')) )
    FROM ZAPATERIA.DETALLE d  
    INNER JOIN ZAPATERIA.FACTURA f  ON d.ID_FACTURA = f.ID_FACTURA
    INNER JOIN ZAPATERIA.PRODUCTO p  ON d.ID_PRODUCTO = p.ID_PRODUCTO
    WHERE TO_CHAR(f.FECHA_FACTURA,'yyyy') = '2020'
    GROUP BY p.ID_PRODUCTO, p.NOMBRE_PRODUCTO
    ORDER BY CANTIDAD DESC
    )WHERE rownum<=3;
    
SELECT * FROM TABLE (dbms_xplan.display);
-- 3. Top 5 de los productos que menos se han vendido en el año 2021.
EXPLAIN PLAN FOR  SELECT PRODUCTO FROM (
    SELECT p.ID_PRODUCTO, p.NOMBRE_PRODUCTO AS PRODUCTO, SUM(d.CANTIDAD) AS CANTIDAD --TO_CHAR(f.FECHA_FACTURA,'yyyy') AS ANIO,CONCAT(TO_CHAR(f.FECHA_FACTURA,'MM'),CONCAT('-',TO_CHAR(f.FECHA_FACTURA,'MONTH')) )
    FROM ZAPATERIA.DETALLE d  
    INNER JOIN ZAPATERIA.FACTURA f  ON d.ID_FACTURA = f.ID_FACTURA
    INNER JOIN ZAPATERIA.PRODUCTO p  ON d.ID_PRODUCTO = p.ID_PRODUCTO
    WHERE TO_CHAR(f.FECHA_FACTURA,'yyyy') = '2021'
    GROUP BY p.ID_PRODUCTO, p.NOMBRE_PRODUCTO
    ORDER BY CANTIDAD ASC
    )WHERE rownum<=5;
SELECT * FROM TABLE (dbms_xplan.display);
-- 4. Top 5 de vendedores que han atendido una mayor cantidad de cliente
EXPLAIN PLAN FOR  SELECT CONCAT(NOMBRE_VENDEDOR,CONCAT( ' ',APELLIDO_VENDEDOR)) as VENDEDOR FROM(
    SELECT  NOMBRE_VENDEDOR, APELLIDO_VENDEDOR, SUM(CLIENTES_A) AS CLIENTES  FROM(
        SELECT c.ID_CLIENTE,  NOMBRE_VENDEDOR, APELLIDO_VENDEDOR, (1) AS CLIENTES_A
        FROM ZAPATERIA.Factura f 
        INNER JOIN  ZAPATERIA.VENDEDOR v  ON f.ID_VENDEDOR = v.ID_VENDEDOR
        INNER JOIN  ZAPATERIA.CLIENTE c ON f.ID_CLIENTE = c.ID_CLIENTE
        GROUP BY c.ID_CLIENTE, v.ID_VENDEDOR, v.NOMBRE_VENDEDOR, v.APELLIDO_VENDEDOR
        )GROUP BY NOMBRE_VENDEDOR, APELLIDO_VENDEDOR
        ORDER BY CLIENTES DESC
        )WHERE rownum<=5;
SELECT * FROM TABLE (dbms_xplan.display);
