CREATE OR REPLACE VIEW Gerencia1.Reporte2 AS
    SELECT PRODUCTO FROM (
        SELECT p.ID_PRODUCTO, p.NOMBRE_PRODUCTO AS PRODUCTO, SUM(d.CANTIDAD) AS CANTIDAD --TO_CHAR(f.FECHA_FACTURA,'yyyy') AS ANIO,CONCAT(TO_CHAR(f.FECHA_FACTURA,'MM'),CONCAT('-',TO_CHAR(f.FECHA_FACTURA,'MONTH')) )
        FROM ZAPATERIA.DETALLE d  
        INNER JOIN ZAPATERIA.FACTURA f  ON d.ID_FACTURA = f.ID_FACTURA
        INNER JOIN ZAPATERIA.PRODUCTO p  ON d.ID_PRODUCTO = p.ID_PRODUCTO
        WHERE TO_CHAR(f.FECHA_FACTURA,'yyyy') = '2020'
        GROUP BY p.ID_PRODUCTO, p.NOMBRE_PRODUCTO
        ORDER BY CANTIDAD DESC
        )WHERE rownum<=3;
        
CREATE OR REPLACE VIEW Ventas1.Reporte3 AS
    SELECT PRODUCTO FROM (
        SELECT p.ID_PRODUCTO, p.NOMBRE_PRODUCTO AS PRODUCTO, SUM(d.CANTIDAD) AS CANTIDAD --TO_CHAR(f.FECHA_FACTURA,'yyyy') AS ANIO,CONCAT(TO_CHAR(f.FECHA_FACTURA,'MM'),CONCAT('-',TO_CHAR(f.FECHA_FACTURA,'MONTH')) )
        FROM ZAPATERIA.DETALLE d  
        INNER JOIN ZAPATERIA.FACTURA f  ON d.ID_FACTURA = f.ID_FACTURA
        INNER JOIN ZAPATERIA.PRODUCTO p  ON d.ID_PRODUCTO = p.ID_PRODUCTO
        WHERE TO_CHAR(f.FECHA_FACTURA,'yyyy') = '2021'
        GROUP BY p.ID_PRODUCTO, p.NOMBRE_PRODUCTO
        ORDER BY CANTIDAD ASC
        )WHERE rownum<=5;
